global:
  scrape_interval: 5s
scrape_configs:
  - job_name: 'universe-microservice-demo'
    metrics_path: '/api/v1/metrics'
    static_configs:
      - targets: ['products-service:8080', 'host.docker.internal:8080']
